### ISSUE TITLE
Spamassassin ALL_TRUSTED

### ISSUE THREAD

**Issue by otbutz** [axllent/spamassassin#6]
docker-compose.yml:

```yml
services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit-data:/data
    ports:
      - 80:8025
      - 25:1025
    environment:
      MP_ENABLE_SPAMASSASSIN: spamassassin:783
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: Europe/Berlin
    depends_on:
      - spamassassin
  spamassassin:
    container_name: spamassassin
    image: axllent/spamassassin
    restart: unless-stopped
```

Sending a test mail to Mailpit results in an overly optimistic spam result:

![image](https://github.com/user-attachments/assets/7c051c4a-7f27-40ca-9308-aa86cb40a705)

**Comment by axllent** [comment]
I really have no idea to be honest. The Spamassassin codebase is huge, and written in perl (which I'm not familiar with), so if you'd like to spend time investigating it that would be great. I've also moved this issue to [axllent/spamassassin](https://github.com/axllent/spamassassin) project as this really relates directly to this (Mailpit just reads the result) :+1:

**Comment by otbutz** [comment]
https://cwiki.apache.org/confluence/display/spamassassin/FixingAllTrusted sound promising. I'll investigate :slightly_smiling_face:

**Comment by otbutz** [comment]
```
trusted_networks 172.17.0.0/16 127.0.0.1 ::1
```

Seems to work :+1:

**Comment by otbutz** [comment]
At least for Mailpit this should be sufficient. But I agree that this needs to be something configurable.

**Comment by axllent** [comment]
Hmm, I'm not actually sure this will achieve what you are wanting, and I cannot replicate my earlier testing / result. From my understanding, all you are achieving is guaranteeing that SpamAssassin knows what your trusted network is, thus guaranteeing that it will apply the `-1 ALL_TRUSTED`.

I have pushed a change (and a new `latest` image) that allows you to set the `INTERNAL_NETWORKS` and `TRUSTED_NETWORKS` variables in your Docker startup, eg:

```yaml
  spamassassin:
    container_name: spamassassin
    image: axllent/spamassassin
    restart: unless-stopped
    environment:
      INTERNAL_NETWORKS: 172.20.0.0/16 172.17.0.0/16
      TRUSTED_NETWORKS: 172.20.0.0/16 172.17.0.0/16
```

Looking forward to your feedback.
